# Exercice of the 7th of October 2020

related to the second course

In [2]:
import numpy as np

## Matrix Operations
![Ex1](1.PNG)

In [4]:
A = np.matrix([[2,3], [4,5]])
B = np.matrix([[1,2], [2,4]])
print("A :\n{}\n\nB :\n{}".format(A, B))

A :
[[2 3]
 [4 5]]

B :
[[1 2]
 [2 4]]


### Transpose of A

In [5]:
def transpose_matrix(M):
    new_M = np.zeros((M.shape[1], M.shape[0]))
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            new_M[j,i]=M[i,j]
    return new_M

print("Own :\n{}\n\nNumpy :\n{}".format(transpose_matrix(A), np.transpose(A)))

Own :
[[2. 4.]
 [3. 5.]]

Numpy :
[[2 4]
 [3 5]]


### Sum A + B

In [6]:
def Add_matrix(A,B):
    if A.shape == B.shape:
        new_M = np.zeros(A.shape)
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                new_M[i,j]=A[i,j]+B[i,j]
        return new_M
    else:
        return "Shapes didn't match"

print("Own :\n{}\n\nNumpy :\n{}".format(Add_matrix(A,B), A+B))

Own :
[[3. 5.]
 [6. 9.]]

Numpy :
[[3 5]
 [6 9]]


### Matrix Product

#### Dot product

In [10]:
def product_matrix(A,B):
    if A.shape[1] == B.shape[0]:
        new_M = np.zeros(A.shape)
        for i in range(A.shape[0]):
            for j in range(B.shape[1]):
                new_M[i,j]=A[i,:]*B[:,j]
        return new_M
    else:
        return "Shapes didn't match"  
    
print("Own :\n{}\n\nNumpy :\n{}".format(product_matrix(A,B), np.dot(A,B)))

Own :
[[ 8. 16.]
 [14. 28.]]

Numpy :
[[ 8 16]
 [14 28]]


#### Element Wise product

In [9]:
def Elem_product_matrix(A,B):
    if A.shape == B.shape:
        new_M = np.zeros(A.shape)
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                new_M[i,j]=A[i,j]*B[i,j]
        return new_M
    else:
        return "Shapes didn't match"
    
print("Own :\n{}\n\nNumpy :\n{}".format(Elem_product_matrix(A,B), np.multiply(A,B)))

Own :
[[ 2.  6.]
 [ 8. 20.]]

Numpy :
[[ 2  6]
 [ 8 20]]


### Matrix Inverse

For 2*2 Matrix :
* Det(M) = ad-bc
* Inv(M) exists if Det(M) != 0
* Inv(M) = 1/Det(M) · ||d, -b|, |-c, a||

In [15]:
def _2_2_matrix_inv(M):
    det = M[0,0]*M[1,1] - M[0,1]*M[1,0]
    if det != 0:
        inv = 1/det * np.matrix([[M[1,1], -M[0,1]], [-M[1,0], M[0,0]]])
        return inv
    else:
        return "Singular Matrix"
    
print("-------------- Matrix A --------------\nOwn :\n{}\n\nNumpy :\n{}".format(_2_2_matrix_inv(A), np.linalg.inv(A)))
print("\n -------------- Matrix B --------------\nOwn :\n{}\n\nNumpy :\n{}".format(_2_2_matrix_inv(B), np.linalg.det(B)))

-------------- Matrix A --------------
Own :
[[-2.5  1.5]
 [ 2.  -1. ]]

Numpy :
[[-2.5  1.5]
 [ 2.  -1. ]]

 -------------- Matrix B --------------
Own :
Singular Matrix

Numpy :
0.0


## Eigen Values and Vectors

![Ex1](2.PNG)

We have :

* A<sup>1</sup> = V · Λ<sup>1</sup> · V<sup>-1</sup>

And :

* A<sup>2</sup> = (V · Λ<sup>1</sup> · V<sup>-1</sup>)<sup>2</sup>
* ⇔ A<sup>2</sup> = (V · Λ<sup>1</sup> · V<sup>-1</sup>) · (V · Λ<sup>1</sup> · V<sup>-1</sup>)
* ⇔ A<sup>2</sup> = V · Λ<sup>1</sup> · V<sup>-1</sup> · V · Λ<sup>1</sup> · V<sup>-1</sup>
* ⇔ A<sup>2</sup> = V · Λ<sup>1</sup> · I · Λ<sup>1</sup> · V<sup>-1</sup>
* ⇔ A<sup>2</sup> = V · Λ<sup>1</sup> · Λ<sup>1</sup> · V<sup>-1</sup>
* ⇔ A<sup>2</sup> = V · Λ<sup>2</sup> · V<sup>-1</sup>

Then we obtain :

* A<sup>k</sup> = (V · Λ<sup>1</sup> · V<sup>-1</sup>)<sup>k</sup>
* ⇔ A<sup>k</sup> = V · Λ<sup>k</sup> · V<sup>-1</sup>

In [28]:
eig_A = np.linalg.eig(A)

print("Own :\n{}\n\nNumpy :\n{}".format(eig_A[1]*(np.diag(np.linalg.eig(A)[0])**3)*np.linalg.inv(eig_A[1]), 
                                        A**3))

Own :
[[116. 153.]
 [204. 269.]]

Numpy :
[[116 153]
 [204 269]]


## Minimizing Least Squares

![Ex1](3.PNG)

Let's define :

* f(x) = ||Ax - b||<sup>2</sup><sub>2</sub>

In order to minimize a function, we look for the derivative of this function, and resolve the equation f'(x) = 0

* f'(x) = 2 * A<sup>T</sup> · (Ax-b)
* Then f'(x) = 0
* ⇔ 2 * A<sup>T</sup> · (Ax-b) = 0
* ⇔ A<sup>T</sup> · (Ax-b) = 0
* ⇔ A<sup>T</sup> · Ax - A<sup>T</sup> · b = 0
* ⇔ A<sup>T</sup> · Ax = A<sup>T</sup> · b
* ⇔ (A<sup>T</sup> · A)<sup>-1</sup> · (A<sup>T</sup> · A) · x = (A<sup>T</sup> · A)<sup>-1</sup> · A<sup>T</sup> · b
* ⇔ I · x = (A<sup>T</sup> · A)<sup>-1</sup> · A<sup>T</sup> · b
* ⇔ x = (A<sup>T</sup> · A)<sup>-1</sup> · A<sup>T</sup> · b

## Gradient Minimization

![Ex1](4.PNG)

**Min<sub>x</sub>  f(x,y)**

* f'(x,y) = 2 * 2 * x - 8 = 4x - 8 

So :

* f'(x,y) = 0
* ⇔ 4x - 8 = 0
* ⇔ 4x = 8
* ⇔ x = 8/4
* ⇔ x = 2

Second Derivative :

* f''(x,y) = 4

* f''(2,y) = 4 is positive, so it means that it's a minimum optimum


**Min<sub>y</sub>  f(x,y)**

* f'(x,y) = 3 * 3 * y<sup>2</sup> - 3 = 9y<sup>2</sup> - 3 

So :

* f'(x,y) = 0
* ⇔ 9y<sup>2</sup> - 3  = 0
* Δ = b<sup>2</sup> - 4ac
* ⇔ Δ = 0<sup>2</sup> - 4 * 9 * (-3)
* ⇔ Δ = 4 * 9 * 3
* ⇔ Δ = 108
* since Δ > 0 It exists two solution to the equation
* Δ<sub>1</sub> = (-b + sqrt(Δ)) / 2a
* ⇔ Δ<sub>1</sub> = (-0 + sqrt(108)) / (2*9)
* ⇔ Δ<sub>1</sub> = sqrt(108) / 18
* Δ<sub>2</sub> = (-b - sqrt(Δ)) / 2a
* ⇔ Δ<sub>2</sub> = - sqrt(108) / 18

Second Derivative :

* f''(x,y) = 9 * 2 * y = 18y

* f''(2,sqrt(108) / 18) = sqrt(108) is positive, so it means that it's a minimum optimum
* f''(2,-sqrt(108) / 18) = -sqrt(108) is negative, so it means that it's a maximum optimum